### ISSUE TITLE
Remove the need for IgnoreTagAspect

### ISSUE THREAD

**Issue by josefd8** [vpTechOSS/gingerspec#42]
Given the current structure of the project, there is a much easier approach for ignoring scenarios based on a tag (which is what IgnoreTagAspect precisely does)

One possible way of making every Feature/Scenario that contain @ignore tag to be ignored is by including this tag in the CucumberOptions annotation in the following way

```
@CucumberOptions(
        features = {"src/test/resources/features/selenium.feature"},
        glue = "com.privalia.qa.specs"
       tags = {"not @ignore"}
)
```

From #39 this can be easily achieved by adding this tag in the CucumberOptionsImpl class in the following way:

```
    @Override
    public String[] tags() {
        LinkedHashSet<String> tags = new LinkedHashSet<>(Arrays.asList(cucumberOptionsAnnotation.tags()));
        tags.add("not @ignore");
        return tags.toArray(new String[]{});
    }
```
Now all runner classes that extends from BaseGTest will include this new tag, effectively, not executing any Feature/Scenario that contains the tag @ignore.

This approach will, however, not give any clue to the user that the Feature/Scenario was ignored (Just like GIngerSpec currently does)

Another approach to creating the same functionality would be to just analyze the tags present in the scenario, if @ignore is present, just do not proceed to execute the scenario, something like this in the BaseGtest class (this, again, in only posible from #39 ):

```
@Override
    @Test(groups = "cucumber", description = "Runs Cucumber Scenarios", dataProvider = "scenarios")
    public void runScenario(PickleEventWrapper pickleWrapper, CucumberFeatureWrapper featureWrapper) throws Throwable {
        List<PickleTag> tags = pickleWrapper.getPickleEvent().pickle.getTags();
        String scenarioName = pickleWrapper.getPickleEvent().pickle.getName();

        if (this.containsTag(tags, "@ignore")) {
            logger.warn("Scenario '" + scenarioName + "' was ignored");
            return;
        }
        super.runScenario(pickleWrapper, featureWrapper);
    }
```
A litle less elegant, but at least a message can be printed to warn the user the scenario was ignored

**Comment by oleksandr0001** [comment]
I am agree with it.

**Comment by josefd8** [comment]
The second solution was applied and is working :)
