### ISSUE TITLE
Añadir un STEP para generar numeros aleatorios

### ISSUE THREAD

**Issue by rommelayala** [vpTechOSS/gingerspec#55]
Agradeceria que añadan un metodo de generacion de numeros aleatorios y no tener que crearlo como un custom STEP, Jose ya me lo ha creado solo falta incluirlo en la libreria.

**Comment by josefd8** [comment]
Hey @rommelayala 

Such step could be included in the next release (2.1.6). Could you elaborate a bit more on what should be the syntax of the step? for example:

- Given I create a random number between '0' and '255' and save it in the variable 'RANDOM'

- GIven I create a random alphanumeric string of '8' chars and save it 'RANDOM'

- GIven I create a random number of '8' chars and save it 'RANDOM'

......etc

Could you provide some feedback about what other use cases could be useful for you ?

**Comment by rommelayala** [comment]
La primera opcion me parace mas adecuada en este momento.
